api_login_check:
    path: /api/token

api_refresh_token:
    path: /api/token/refresh

controllers:
    resource: ../src/Controller/
    type: attribute
    prefix: /api
    defaults: { _api_respond: true }